### ISSUE TITLE
create landing page

### ISSUE THREAD

**Issue by bmkersey** [BenHuf/encounter-gen#3]
](url
![mockupmain](https://user-images.githubusercontent.com/101957636/167966736-4bf9d430-18be-4faa-97d7-f1c0001565e3.png)
)

Make landing page close-ish to this mock up

**Comment by BenHuf** [comment]
I omitted the "Deck" stacking feature and will create an issue for adding it in future development -- For MVP however we have a workable landing page!!! Closing this issue.
